[general]
import = [ './colors.toml' ]

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 10.5

[window]
opacity = 1

[cursor]
style = { shape = "Underline", blinking = "Never" }

[env]
TERM = "xterm-256color"
