# Colors (Zenburn)
# Orginally designed by jnurmine for vim.

# Default colors
[colors.primary]
background = '#000000'
foreground = '#DCDCCC'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#DE6E7C'
green   = '#819B69'
yellow  = '#B77E64'
blue    = '#6099C0'
magenta = '#B279A7'
cyan    = '#66A5AD'
white   = '#FFFFFF'

# Bright colors
[colors.bright]
black   = '#403833'
red     = '#E8838F'
green   = '#8BAE68'
yellow  = '#D68C67'
blue    = '#61ABDA'
magenta = '#CF86C1'
cyan    = '#65B8C1'
white   = '#888F94'
