
#   ██░ ██ ▓█████  ██▓     ██▓▒██   ██▒
#  ▓██░ ██▒▓█   ▀ ▓██▒    ▓██▒▒▒ █ █ ▒░
#  ▒██▀▀██░▒███   ▒██░    ▒██▒░░  █   ░
#  ░▓█ ░██ ▒▓█  ▄ ▒██░    ░██░ ░ █ █ ▒ 
#  ░▓█▒░██▓░▒████▒░██████▒░██░▒██▒ ▒██▒
#   ▒ ░░▒░▒░░ ▒░ ░░ ▒░▓  ░░▓  ▒▒ ░ ░▓ ░
#   ▒ ░▒░ ░ ░ ░  ░░ ░ ▒  ░ ▒ ░░░   ░▒ ░
#   ░  ░░ ░   ░     ░ ░    ▒ ░ ░    ░  
#   ░  ░  ░   ░  ░    ░  ░ ░   ░    ░  

# Nord Theme
theme = "rose_pine"

# Editor Settings
[editor]
line-number = "relative"
mouse = false
cursorline = true 
auto-completion = true
auto-format = true
auto-save = true
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
bufferline = "multiple"

# Status line
[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["position", "spacer","total-line-numbers", "spacer", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# LSP
[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
snippets = true
goto-reference-include-declaration = true

# Cursor shape
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Indentation
[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# Wrap
[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-indicator = ""

# Smart tab
[editor.smart-tab]
enable = true
