splash = false

# wallpaper {
#     monitor = eDP-1
#     path = /home/barac/.config/wallpapers/1742499302802844.jpg
#     # path = /home/barac/.config/wallpapers/1767498429429423.png
#     # path = /home/barac/.config/wallpapers/1753194650143372.jpg
#     # path = /home/barac/.config/wallpapers/1753194618291837.jpg
#     fit_mode = contain
# }

wallpaper {
    monitor = HDMI-A-1
    path = /home/barac/.config/wallpapers/1742499302802844.jpg
    # path = /home/barac/.config/wallpapers/1767498429429423.png
    # path = /home/barac/.config/wallpapers/1753194650143372.jpg
    # path = /home/barac/.config/wallpapers/1753194618291837.jpg
    fit_mode = contain
}

