# Keep the current directory
unbind C-b

set -g prefix C-f

set -g default-terminal "tmux-256color"

bind C-f send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# rosebones_dark theme
# See: https://github.com/zenbones-theme/zenbones.nvim/blob/main/extras/tmux/rosebones_dark.tmux
# This file is auto-generated by shipwright.nvim
set -g status-left ' #[fg=#C4A7E7,bold]#{s/root//:client_key_table} '
set -g status-right '#[fg=#C4A7E7,bold] [#S]#[fg=#C4A7E7,bold] [%d/%m] #[fg=#C4A7E7,bold][%I:%M%p] '
set -g status-style fg='#C4A7E7',bg='#000000'

set -g window-status-current-style fg='#C4A7E7',bg='#000000',bold

set -g pane-border-style fg='#C4A7E7'
set -g pane-active-border-style fg='#C4A7E7'

set -g message-style fg='#1A1825',bg='#523A39'

set -g display-panes-active-colour '#C4A7E7'
set -g display-panes-colour '#C4A7E7'

set -g clock-mode-colour '#C4A7E7'

set -g mode-style fg='#1A1825',bg='#523A39'

